!     Allocate ICM arrays and initialize all of them
!     Joseph Zhang

      subroutine icm_init

      use schism_msgp, only : parallel_abort
      USE icm_mod
      USE icm_sed_mod
      implicit none

      integer :: istat

      allocate(dep(iZ),Sal(iZ),Temp(iZ),ZB1(iZ,2),ZB2(iZ,2),PB1(iZ,2),PB2(iZ,2),PB3(iZ,2), &
     &RPOC(iZ,2),LPOC(iZ,2),DOCA(iZ,2),RPON(iZ,2),LPON(iZ,2),DON(iZ,2),NH4(iZ,2),NO3(iZ,2), &
     &RPOP(iZ,2),LPOP(iZ,2),DOP(iZ,2),PO4t(iZ,2),PO4d(iZ,2),SU(iZ,2),SAt(iZ,2),SAd(iZ,2), &
     &COD(iZ,2),DOC(iZ,2),rKRPOC(iZ),rKLPOC(iZ),rKDOCA(iZ),rKRPON(iZ),rKLPON(iZ),rKDON(iZ), &
     &rKRPOP(iZ),rKLPOP(iZ),rKDOP(iZ),rNitN(iZ),rKSUA(iZ),rrKCOD(iZ),CSPP1(iZ),CSPI1(iZ), &
     &BMZ(iB,iZ),CCZD1(iB,iZ),CCZD0(iB,iZ),CNZR1(iB,iZ),CNZL1(iB,iZ),CNZD1(iB,iZ), &
     &CNZI1(iB,iZ),CPZR1(iB,iZ),CPZL1(iB,iZ),CPZD1(iB,iZ),CPZI1(iB,iZ),CSZP1(iB,iZ),CSZI1(iB,iZ), &
     &BMP(iA,iZ),BPR(iA,iZ),CCPD1(iA,iZ),CCPD0(iA,iZ),CNPR1(iA,iZ),CNPL1(iA,iZ),CNPD1(iA,iZ),CNPI1(iA,iZ), &
     &CPPR1(iA,iZ),CPPL1(iA,iZ),CPPD1(iA,iZ),CPPI1(iA,iZ),GP(iA,iZ),GZ(iZ,8,iB), &
     &xBRPOC(iX),xBLPOC(iX),xBDOCA(iX),xBRPON(iX),xBLPON(iX),xBDON(iX),xBNH4(iX),xBNO3(iX), &
     &xBRPOP(iX),xBLPOP(iX),xBDOP(iX),xBPO4t(iX),xBSU(iX),xBSAt(iX),xBCOD(iX),xBDO(iX), &
     &PR2(iA,iZ),PR3(iA,iZ),G(iA,iZ),TSED(iX,iT),ieflag(iX),icflag(iX),ie_do_flag(iX), &
     &ie_light_flag(iX),OpenOceanFlag(iX),KKLC(iX),KKRO(iX),WReab(iX),WMS(iX),WWPRPOC(iX), &
     &WWPLPOC(iX),WWPDOCA(iX),WWPRPON(iX),WWPLPON(iX),WWPDON(iX),WWPNH4(iX),WWPNO3(iX), &
     &WWPRPOP(iX),WWPLPOP(iX),WWPDOP(iX),WWPPO4t(iX),WWPSU(iX),WWPSAt(iX),WWPCOD(iX),WWPDO(iX), &
     &WWPSalt(iX),SFA(SED_NBB),AG3CFL(SED_NBB),AG3NFL(SED_NBB),AG3PFL(SED_NBB),ASDTMP(SED_NBB), &
     &SED_B1(SED_NBB),SED_B2(SED_NBB),SED_B3(SED_NBB),SED_LPOP(SED_NBB),SED_RPOP(SED_NBB), &
     &SED_LPON(SED_NBB),SED_RPON(SED_NBB),SED_LPOC(SED_NBB),SED_RPOC(SED_NBB),SED_SU(SED_NBB), &
     &SED_PO4(SED_NBB),SED_NH4(SED_NBB),SED_NO3(SED_NBB),SED_SA(SED_NBB),SED_DO(SED_NBB), &
     &SED_COD(SED_NBB),SED_SALT(SED_NBB),SED_T(SED_NBB),SSI(SED_NBB),SED_BL(SED_NBB,3),ZD(SED_NBB), &
     &SFLUXP(SED_NBB),SF_RPOP(SED_NBB),SFLUXN(SED_NBB),SF_RPON(SED_NBB),SFLUXC(SED_NBB), &
     &SF_RPOC(SED_NBB),JSUSF(SED_NBB),SF_SU(SED_NBB),SF_SSI(SED_NBB),SEDCSAV(SED_NBB), &
     &SEDNSAV(SED_NBB),SEDPSAV(SED_NBB),SEDNH4SAV(SED_NBB),SEDPO4SAV(SED_NBB),SEDDOSAV(SED_NBB), &
     &DFEEDM1S(SED_NBB),BBM(SED_NBB),WSSBNET(SED_NBB),WSLBNET(SED_NBB),WSRBNET(SED_NBB), &
     &WS1BNET(SED_NBB),WS2BNET(SED_NBB),WS3BNET(SED_NBB),WSUBNET(SED_NBB),VSED(SED_NBB), &
     &VPMIX(SED_NBB),VDMIX(SED_NBB),WSSNET(SED_NBB),WSLNET(SED_NBB),WSRNET(SED_NBB), &
     &WS1NET(SED_NBB),WS2NET(SED_NBB),WS3NET(SED_NBB),WSUNET(SED_NBB),FRPOP(SED_NBB,3), &
     &FRPON(SED_NBB,3),FRPOC(SED_NBB,3),CTEMP(SED_NBB),CPOS(SED_NBB),HSED(SED_NBB), &
     &CPIP(SED_NBB),CNO3(SED_NBB),CNH4(SED_NBB),CCH4(SED_NBB),CSO4(SED_NBB),CPOP(SED_NBB,3), &
     &CPON(SED_NBB,3),CPOC(SED_NBB,3),FLXPOP(SED_NBB,3),FLXPON(SED_NBB,3),FLXPOC(SED_NBB,3), &
     &FLXPOS(SED_NBB),PPFWS(SED_NBB),PNFWS(SED_NBB),PCFWS(SED_NBB),PSFWS(SED_NBB),SSFWS(SED_NBB), &
     &CH4T2TM1S(SED_NBB),CH41TM1S(SED_NBB),SO4T2TM1S(SED_NBB),BENSTR1S(SED_NBB),BFORMAXS(SED_NBB), &
     &ISWBENS(SED_NBB),POP1TM1S(SED_NBB),POP2TM1S(SED_NBB),POP3TM1S(SED_NBB),PON1TM1S(SED_NBB), &
     &PON2TM1S(SED_NBB),PON3TM1S(SED_NBB),POC1TM1S(SED_NBB),POC2TM1S(SED_NBB),POC3TM1S(SED_NBB), &
     &PSITM1S(SED_NBB),PATCH(SED_NBB),SH(SED_NBB),NH41TM1S(SED_NBB),NO31TM1S(SED_NBB), &
     &HS1TM1S(SED_NBB),SI1TM1S(SED_NBB),PO41TM1S(SED_NBB),NH4T2TM1S(SED_NBB),NO3T2TM1S(SED_NBB), &
     &HST2TM1S(SED_NBB),SIT2TM1S(SED_NBB),PO4T2TM1S(SED_NBB),DF_GROW(SED_NBB),DF_RESP(SED_NBB), &
     &DF_PRED(SED_NBB),DF_MORT(SED_NBB),SFEED(SED_NBB,3),SF_SA(SED_NBB),SF_PIP(SED_NBB), &
     &sed_BENDO(SED_NBB),MTVEL(SED_NBB),sed_BENNH4(SED_NBB),sed_BENNO3(SED_NBB),BENPO4(SED_NBB), &
     &BENDOC(SED_NBB),sed_BENCOD(SED_NBB),BENCH4G(SED_NBB),BENCH4A(SED_NBB),BENSA(SED_NBB), &
     &BENDEN(SED_NBB),SED_BURIALN(SED_NBB),SED_BURIALP(SED_NBB),SED_BURIALC(SED_NBB), &
     &DIAGENC(SED_NBB),FIB(SED_NBB),BLITE(SED_NBB),IATBOT(SED_NBB),NLB(SED_NBB),PLB(SED_NBB), &
     &BMB(SED_NBB),PB(SED_NBB),NPPB(SED_NBB),PRB(SED_NBB),BANH4(SED_NBB),BANO3(SED_NBB), &
     &BAPO4(SED_NBB),BADO(SED_NBB),BADOC(SED_NBB),BAPOC(SED_NBB),BAPON(SED_NBB),BAPOP(SED_NBB),stat=istat)
      if(istat/=0) call parallel_abort('ICM_INIT: alloc(1)')

      !Init. 
      dep=0; Sal=0; Temp=0; ZB1=0; ZB2=0; PB1=0; PB2=0; PB3=0;  
      RPOC=0; LPOC=0; DOCA=0; RPON=0; LPON=0; DON=0; NH4=0; NO3=0;  
      RPOP=0; LPOP=0; DOP=0; PO4t=0; PO4d=0; SU=0; SAt=0; SAd=0;  
      COD=0; DOC=0; rKRPOC=0; rKLPOC=0; rKDOCA=0; rKRPON=0; rKLPON=0; rKDON=0;  
      rKRPOP=0; rKLPOP=0; rKDOP=0; rNitN=0; rKSUA=0; rrKCOD=0; CSPP1=0; CSPI1=0;  
      BMZ=0; CCZD1=0; CCZD0=0; CNZR1=0; CNZL1=0; CNZD1=0;  
      CNZI1=0; CPZR1=0; CPZL1=0; CPZD1=0; CPZI1=0; CSZP1=0; CSZI1=0;  
      BMP=0; CCPD1=0; CCPD0=0; CNPR1=0; CNPL1=0; CNPD1=0; CNPI1=0;  
      CPPR1=0; CPPL1=0; CPPD1=0; CPPI1=0; GP=0; GZ=0;  
      xBRPOC=0; xBLPOC=0; xBDOCA=0; xBRPON=0; xBLPON=0; xBDON=0; xBNH4=0; xBNO3=0;  
      xBRPOP=0; xBLPOP=0; xBDOP=0; xBPO4t=0; xBSU=0; xBSAt=0; xBCOD=0; xBDO=0;  
      PR2=0; PR3=0; G=0; TSED=0; ieflag=0; icflag=0; ie_do_flag=0;  
      ie_light_flag=0; OpenOceanFlag=0; KKLC=0; KKRO=0; WReab=0; WMS=0; WWPRPOC=0;  
      WWPLPOC=0; WWPDOCA=0; WWPRPON=0; WWPLPON=0; WWPDON=0; WWPNH4=0; WWPNO3=0;  
      WWPRPOP=0; WWPLPOP=0; WWPDOP=0; WWPPO4t=0; WWPSU=0; WWPSAt=0; WWPCOD=0; WWPDO=0;  
      WWPSalt=0; SFA=0; AG3CFL=0; AG3NFL=0; AG3PFL=0; ASDTMP=0;  
      SED_B1=0; SED_B2=0; SED_B3=0; SED_LPOP=0; SED_RPOP=0;  
      SED_LPON=0; SED_RPON=0; SED_LPOC=0; SED_RPOC=0; SED_SU=0;  
      SED_PO4=0; SED_NH4=0; SED_NO3=0; SED_SA=0; SED_DO=0;  
      SED_COD=0; SED_SALT=0; SED_T=0; SSI=0; SED_BL=0; ZD=0;  
      SFLUXP=0; SF_RPOP=0; SFLUXN=0; SF_RPON=0; SFLUXC=0;  
      SF_RPOC=0; JSUSF=0; SF_SU=0; SF_SSI=0; SEDCSAV=0;  
      SEDNSAV=0; SEDPSAV=0; SEDNH4SAV=0; SEDPO4SAV=0; SEDDOSAV=0;  
      DFEEDM1S=0; BBM=0; WSSBNET=0; WSLBNET=0; WSRBNET=0;  
      WS1BNET=0; WS2BNET=0; WS3BNET=0; WSUBNET=0; VSED=0;  
      VPMIX=0; VDMIX=0; WSSNET=0; WSLNET=0; WSRNET=0;  
      WS1NET=0; WS2NET=0; WS3NET=0; WSUNET=0; FRPOP=0;
      FRPON=0; FRPOC=0; CTEMP=0; CPOS=0; HSED=0;  
      CPIP=0; CNO3=0; CNH4=0; CCH4=0; CSO4=0; CPOP=0;
      CPON=0; CPOC=0; FLXPOP=0; FLXPON=0; FLXPOC=0;  
      FLXPOS=0; PPFWS=0; PNFWS=0; PCFWS=0; PSFWS=0; SSFWS=0;  
      CH4T2TM1S=0; CH41TM1S=0; SO4T2TM1S=0; BENSTR1S=0; BFORMAXS=0;  
      ISWBENS=0; POP1TM1S=0; POP2TM1S=0; POP3TM1S=0; PON1TM1S=0;  
      PON2TM1S=0; PON3TM1S=0; POC1TM1S=0; POC2TM1S=0; POC3TM1S=0;  
      PSITM1S=0; PATCH=0; SH=0; NH41TM1S=0; NO31TM1S=0;  
      HS1TM1S=0; SI1TM1S=0; PO41TM1S=0; NH4T2TM1S=0; NO3T2TM1S=0;  
      HST2TM1S=0; SIT2TM1S=0; PO4T2TM1S=0; DF_GROW=0; DF_RESP=0;  
      DF_PRED=0; DF_MORT=0; SFEED=0; SF_SA=0; SF_PIP=0;  
      sed_BENDO=0; MTVEL=0; sed_BENNH4=0; sed_BENNO3=0; BENPO4=0;  
      BENDOC=0; sed_BENCOD=0; BENCH4G=0; BENCH4A=0; BENSA=0;  
      BENDEN=0; SED_BURIALN=0; SED_BURIALP=0; SED_BURIALC=0;  
      DIAGENC=0; FIB=0; BLITE=0; IATBOT=0; NLB=0; PLB=0;  
      BMB=0; PB=0; NPPB=0; PRB=0; BANH4=0; BANO3=0;  
      BAPO4=0; BADO=0; BADOC=0; BAPOC=0; BAPON=0; BAPOP=0;

      end subroutine icm_init
